# Beyond 10 workspaces
bindd = SUPER ALT, EQUAL, Go to workpsace, exec, notify-send -t 0 " Go to workspace" "Type number + Enter\n(Esc to cancel)" && hyprctl dispatch submap workspace-go-to
bindd = SUPER ALT SHIFT, EQUAL, Move active window to workspace, exec, notify-send -t 0 " Move window to workspace" "Type number + Enter\n(Esc to cancel)" && hyprctl dispatch submap workspace-move-to

submap = workspace-go-to
bind = , 0, exec, system-workspaces-10-plus go-to 0
bind = , 1, exec, system-workspaces-10-plus go-to 1
bind = , 2, exec, system-workspaces-10-plus go-to 2
bind = , 3, exec, system-workspaces-10-plus go-to 3
bind = , 4, exec, system-workspaces-10-plus go-to 4
bind = , 5, exec, system-workspaces-10-plus go-to 5
bind = , 6, exec, system-workspaces-10-plus go-to 6
bind = , 7, exec, system-workspaces-10-plus go-to 7
bind = , 8, exec, system-workspaces-10-plus go-to 8
bind = , 9, exec, system-workspaces-10-plus go-to 9
bind = , Return, exec, system-workspaces-10-plus go-to enter
bind = , Escape, exec, system-workspaces-10-plus go-to escape
submap = reset

submap = workspace-move-to
bind = , 0, exec, system-workspaces-10-plus move-to 0
bind = , 1, exec, system-workspaces-10-plus move-to 1
bind = , 2, exec, system-workspaces-10-plus move-to 2
bind = , 3, exec, system-workspaces-10-plus move-to 3
bind = , 4, exec, system-workspaces-10-plus move-to 4
bind = , 5, exec, system-workspaces-10-plus move-to 5
bind = , 6, exec, system-workspaces-10-plus move-to 6
bind = , 7, exec, system-workspaces-10-plus move-to 7
bind = , 8, exec, system-workspaces-10-plus move-to 8
bind = , 9, exec, system-workspaces-10-plus move-to 9
bind = , Return, exec, system-workspaces-10-plus move-to enter
bind = , Escape, exec, system-workspaces-10-plus move-to escape
submap = reset
